# Generated by Django 5.0 on 2024-04-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_supreme_court'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supreme_court',
        ),
    ]
